files:
  - source: /app/src/main/res/values/strings*.xml
    ignore:
      - /app/src/main/res/values/strings_no_translate.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
